#ifndef __J2534main__
#define __J2534main__

/**
@file
Subclass of frmMainBase, which is generated by wxFormBuilder.
*/

#include "UI_stuff.h"

//// end generated include

/** Implementing frmMainBase */
class J2534main : public frmMainBase
{
	protected:
		// Handlers for frmMainBase events.
		void DiscoverButton_Click( wxCommandEvent& event );
		void BoxOpenButton_Click( wxCommandEvent& event );
		void BoxCloseButton_Click( wxCommandEvent& event );
		void ConnectButton_Click( wxCommandEvent& event );
		void DisconnectButton_Click( wxCommandEvent& event );
		void ExecSlowInitButton_Click( wxCommandEvent& event );
	public:
		/** Constructor */
		J2534main( wxWindow* parent );
	//// end generated class members
	
};

#endif // __J2534main__
